#include "TFile.h"
#include "TTree.h"
#include "TLorentzVector.h"

#include <vector>
#include <iostream>

using namespace std;

/// \file
/// \ingroup tutorial_tree
///
/// Example of Root macro to copy a subset of a Tree to a new Tree, selecting entries.
///
/// Only selected entries are copied to the new Tree.
/// The input file has been generated by the program in $ROOTSYS/test/Event
/// with `Event 1000 1 99 1`
/// \macro_code
/// \author Rene Brun

const int nMu_min = 2;
const double muPtCut = 20;
const double muEtaCut = 2.4;
// Run-II tight cuts (https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideMuonIdRun2#Tight_Muon)
const float muChi2NDFCut   = 10;
const float muInnerD0Cut   = 0.3;// same as HIN-16-004, was 0.2
const float muInnerDzCut   = 20;// same as HIN-16-004, was 0.5
const int   muMuonHitsCut  = 0;
const int   muStationsCut  = 1;
const int   muTrkLayersCut = 5;
const int   muPixelHitsCut = 0;

void makeMiniTree(const char* infile, const char* outfile, bool isData=false) {

   //Get old file, old tree and set top branch address
   TFile *oldfile = new TFile(infile);

   TTree *hltTree_old = (TTree*)oldfile->Get("hltanalysis/HltTree");
   TTree *filterTree_old = (TTree*)oldfile->Get("skimanalysis/HltTree");
   TTree *pfTreeCS_old = (TTree*)oldfile->Get("pfcandAnalyzerCS/pfTree");
   TTree *pfTree_old = (TTree*)oldfile->Get("pfcandAnalyzer/pfTree");
   TTree *hiTree_old = (TTree*)oldfile->Get("hiEvtAnalyzer/HiTree");
   TTree *particleTree_old = (TTree*)oldfile->Get("ggHiNtuplizer/EventTree");
   
   Long64_t nentries = hltTree_old->GetEntries();
   
   int L3Mu15, L2Mu15;
   hltTree_old->SetBranchStatus("*",0);
   hltTree_old->SetBranchStatus("HLT_HIL*Mu15_v*",1);
   hltTree_old->SetBranchAddress("HLT_HIL3Mu15_v1",&L3Mu15);
   hltTree_old->SetBranchAddress("HLT_HIL2Mu15_v2",&L2Mu15);

   int phfCoincFilter, HBHENoiseFilterResult, pprimaryVertexFilter, pcollisionEventSelection;
   filterTree_old->SetBranchStatus("*",0);
   filterTree_old->SetBranchAddress("phfCoincFilter3",&phfCoincFilter);
   filterTree_old->SetBranchAddress("HBHENoiseFilterResult",&HBHENoiseFilterResult);
   filterTree_old->SetBranchAddress("pprimaryVertexFilter",&pprimaryVertexFilter);
   filterTree_old->SetBranchAddress("pcollisionEventSelection",&pcollisionEventSelection);

   hiTree_old->SetBranchStatus("*",0);
   hiTree_old->SetBranchStatus("run",1);
   hiTree_old->SetBranchStatus("evt",1);
   hiTree_old->SetBranchStatus("lumi",1);
   hiTree_old->SetBranchStatus("hiBin",1);
   hiTree_old->SetBranchStatus("vz",1);

   Int_t           nMu = 0;
   vector<float>   *muPt = 0;
   vector<float>   *muEta = 0;
   vector<float>   *muPhi = 0;
   vector<int>     *muCharge = 0;
   vector<float>   *muChi2NDF = 0;
   vector<float>   *muInnerD0 = 0;
   vector<float>   *muInnerDz = 0;
   vector<int>     *muTrkLayers = 0;
   vector<int>     *muPixelHits = 0;
   vector<int>     *muMuonHits = 0;
   vector<int>     *muStations = 0;
   particleTree_old->SetBranchStatus("*",0);
   particleTree_old->SetBranchStatus("nMC",1);
   particleTree_old->SetBranchStatus("mcPID",1);
   particleTree_old->SetBranchStatus("mcPt",1);
   particleTree_old->SetBranchStatus("mcEta",1);
   particleTree_old->SetBranchStatus("mcPhi",1);
   particleTree_old->SetBranchStatus("mcMass",1);
   particleTree_old->SetBranchStatus("mcMomPID",1);
   particleTree_old->SetBranchStatus("nMu",1);
   particleTree_old->SetBranchStatus("muPt",1);
   particleTree_old->SetBranchStatus("muEta",1);
   particleTree_old->SetBranchStatus("muPhi",1);
   particleTree_old->SetBranchStatus("muCharge",1);
   particleTree_old->SetBranchStatus("muChi2NDF",1);
   particleTree_old->SetBranchStatus("muInnerD0",1);
   particleTree_old->SetBranchStatus("muInnerDz",1);
   particleTree_old->SetBranchStatus("muMuonHits",1);
   particleTree_old->SetBranchStatus("muStations",1);
   particleTree_old->SetBranchStatus("muTrkLayers",1);
   particleTree_old->SetBranchStatus("muPixelHits",1);    
   particleTree_old->SetBranchAddress("nMu",&nMu);
   particleTree_old->SetBranchAddress("muPt",&muPt);
   particleTree_old->SetBranchAddress("muPhi",&muPhi);
   particleTree_old->SetBranchAddress("muEta",&muEta);
   particleTree_old->SetBranchAddress("muCharge",&muCharge);
   particleTree_old->SetBranchAddress("muChi2NDF",&muChi2NDF);
   particleTree_old->SetBranchAddress("muInnerD0",&muInnerD0);
   particleTree_old->SetBranchAddress("muInnerDz",&muInnerDz);
   particleTree_old->SetBranchAddress("muMuonHits",&muMuonHits);
   particleTree_old->SetBranchAddress("muStations",&muStations);
   particleTree_old->SetBranchAddress("muTrkLayers",&muTrkLayers);
   particleTree_old->SetBranchAddress("muPixelHits",&muPixelHits);    
   
   pfTree_old->SetBranchStatus("*",0);
   pfTree_old->SetBranchStatus("nPFpart",1);
   pfTree_old->SetBranchStatus("pfId",1);
   pfTree_old->SetBranchStatus("pfEta",1);
   pfTree_old->SetBranchStatus("pfPt",1);
   pfTree_old->SetBranchStatus("pfPhi",1);
   pfTree_old->SetBranchStatus("pfEnergy",1);
   pfTreeCS_old->SetBranchStatus("*",0);
   pfTreeCS_old->SetBranchStatus("nPFpart",1);
   pfTreeCS_old->SetBranchStatus("pfId",1);
   pfTreeCS_old->SetBranchStatus("pfEta",1);
   pfTreeCS_old->SetBranchStatus("pfPt",1);
   pfTreeCS_old->SetBranchStatus("pfPhi",1);
   pfTreeCS_old->SetBranchStatus("pfEnergy",1);

   Int_t           nMu_new = 0;
   vector<float>   *muPt_new = new vector<float>();
   vector<float>   *muEta_new = new vector<float>();
   vector<float>   *muPhi_new = new vector<float>();
   vector<int>     *muCharge_new = new vector<int>();

   //Create a new file + a clone of old tree in new file
   TFile *newfile = new TFile(outfile,"recreate");
   TTree *hltTree_new = hltTree_old->CloneTree(0); hltTree_new->SetName("hltTree");
   TTree *pfTree_new = pfTree_old->CloneTree(0); pfTree_new->SetName("pfTree");
   TTree *pfTreeCS_new = pfTreeCS_old->CloneTree(0); pfTreeCS_new->SetName("pfTreeCS");
   TTree *hiTree_new = hiTree_old->CloneTree(0); hiTree_new->SetName("hiTree");
   TTree *particleTree_new = particleTree_old->CloneTree(0); particleTree_new->SetName("particleTree");

   nentries = 1000;
   int entryDiv = ((int)(nentries/20));
   for (Long64_t i=0;i<nentries; i++) {
      if(i%entryDiv == 0 && nentries >= 10000) std::cout << "Entry # " << i << "/" << nentries << std::endl;
      hltTree_old->GetEntry(i);
      if (L3Mu15==0 && L2Mu15==0) continue;
      
      if (isData) {
         filterTree_old->GetEntry(i);
         if (!phfCoincFilter || !HBHENoiseFilterResult || !pprimaryVertexFilter || !pcollisionEventSelection) continue;
      }
      
      particleTree_old->GetEntry(i);
      if (nMu<nMu_min) continue; // look at Z events: at least 2 muons
      nMu_new=0; muPt_new->clear(); muEta_new->clear(); muPhi_new->clear(); muCharge_new->clear();
      for (int muIter=0; muIter<nMu; muIter++) {
         if(muPt->at(muIter)<muPtCut || fabs(muEta->at(muIter))>muEtaCut) continue;
         // apply tight ID cuts
         if(muChi2NDF->at(muIter) >= muChi2NDFCut) continue;
         if(TMath::Abs(muInnerD0->at(muIter)) > muInnerD0Cut) continue;
         if(TMath::Abs(muInnerDz->at(muIter)) > muInnerDzCut) continue;
         if(muMuonHits->at(muIter) <= muMuonHitsCut) continue;
         if(muStations->at(muIter) <= muStationsCut) continue;
         if(muTrkLayers->at(muIter) <= muTrkLayersCut) continue;
         if(muPixelHits->at(muIter) <= muPixelHitsCut) continue;
         nMu_new++;
         muPt_new->push_back(muPt->at(muIter));
         muEta_new->push_back(muEta->at(muIter));
         muPhi_new->push_back(muPhi->at(muIter));
         muCharge_new->push_back(muCharge->at(muIter));
      }
      if (nMu_new<nMu_min) continue;
      if (muCharge_new->at(0)==muCharge_new->at(1)) continue;
      TLorentzVector mu0; mu0.SetPtEtaPhiM(muPt_new->at(0), muEta_new->at(0), muPhi_new->at(0), 106e-3);
      TLorentzVector mu1; mu1.SetPtEtaPhiM(muPt_new->at(1), muEta_new->at(1), muPhi_new->at(1), 106e-3);
      if ((mu0+mu1).M()<30) continue;
      muPt = muPt_new;
      muEta = muEta_new;
      muPhi = muPhi_new;
      muCharge = muCharge_new;
      
      pfTree_old->GetEntry(i);
      pfTreeCS_old->GetEntry(i);
      hiTree_old->GetEntry(i);
      hltTree_new->Fill();
      pfTree_new->Fill();
      pfTreeCS_new->Fill();
      hiTree_new->Fill();
      particleTree_new->Fill();
      muPt = 0;
      muEta = 0;
      muPhi = 0;
      muCharge = 0;
   }
   hltTree_new->AutoSave();
   pfTree_new->AutoSave();
   pfTreeCS_new->AutoSave();
   hiTree_new->AutoSave();
   particleTree_new->AutoSave();
   delete oldfile;
   delete newfile;
}
